- hosts: localhost
  vars_files:
  - vars.yaml

  tasks:
  - name: Checkout repos
    git:
     repo: 'https://github.com/geneontology/{{ item }}.git'
     dest: ./{{ item }}
     version: '{{ branch }}'
     force: yes
    with_items:
      - '{{ repos }}'

  - name: build minerva container image
    docker_image:
      name: 'minerva:{{ tag }}'
      source: build
      build:
        dockerfile: '{{ cwd }}/docker/Dockerfile.minerva'
        path: '{{ cwd }}/minerva'
        pull: no
      state: present

  - name: build noctua container image
    docker_image:
      name: 'noctua:{{ tag }}'
      source: build
      build:
        dockerfile: '{{ cwd }}/docker/Dockerfile.noctua'
        path: '{{ cwd }}/noctua'
        pull: no
      state: present
