- hosts: localhost
  vars_files:
  - vars.yaml

  tasks:
  - name: Checkout repos
    git:
     repo: 'git@github.com:geneontology/{{ item }}.git'
     dest: ./{{ item }}
     version: '{{ branch }}'
     force: yes
    with_items:
      - '{{ repos }}'
    tags:
      - clone_repos

  - name: build minerva container image
    docker_image:
      name: 'minerva:{{ tag }}'
      source: build
      build:
        dockerfile: '{{ cwd }}/docker/Dockerfile.minerva'
        path: '{{ cwd }}/minerva'
        pull: no
      state: present
    tags:
      - build_docker_images
      - build_minerva_image

  - name: build noctua container image
    docker_image:
      name: 'noctua:{{ tag }}'
      source: build
      build:
        dockerfile: '{{ cwd }}/docker/Dockerfile.noctua'
        path: '{{ cwd }}/noctua'
        pull: no
      state: present
    tags:
      - build_docker_images
      - build_noctua_image
