- hosts: localhost
  vars_files:
  - docker-vars.yaml

  tasks:
  - name: Push golr to dockerhub
    shell: docker push '{{ docker_hub_user }}/golr:{{ tag }}'

  - name: Push noctua to dockerhub
    shell: docker push '{{ docker_hub_user }}/noctua:{{ tag }}'

  - name: Push minerva to docker hub
    shell: docker push '{{ docker_hub_user }}/minerva:{{ tag }}'
