version: '3'
services:

  minerva:
    hostname: minerva 
    container_name: minerva 
    environment:
      JAVA_OPTS: "{{ minerva_java_opts }}"
    volumes:
      - {{ stage_dir }}:/var/minerva
    image: minerva:{{ tag }}
    restart: unless-stopped

  barista:
    hostname: barista 
    container_name: barista  
    volumes:
      - {{ stage_dir }}:/stage_dir
      - {{ stage_dir }}/conf/startup.yaml:/app/startup.yaml
    image: noctua:{{ tag }}
    command: ./node_modules/.bin/gulp run-barista
    restart: unless-stopped
    depends_on:
      - minerva 

  noctua:
    hostname: noctua 
    container_name: noctua  
    volumes:
      - {{ stage_dir }}:/stage_dir
      - {{ stage_dir }}/conf/startup.yaml:/app/startup.yaml
    image: noctua:{{ tag }}
    command: ./node_modules/.bin/gulp run-noctua
    restart: unless-stopped
    depends_on:
      - minerva 
      - barista 

  apache_barista:
    hostname: apache_barista 
    container_name: apache_barista
    image: httpd:latest
    restart: unless-stopped
    volumes:
      - {{ stage_dir }}/httpd-confs/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - {{ stage_dir }}/httpd-confs/httpd-vhosts-barista.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    ports:
      - "{{barista_proxy_port }}:80"
    depends_on:
      - barista 

  apache_noctua:
    hostname: apache_noctua
    container_name: apache_noctua
    image: httpd:latest
    restart: unless-stopped
    volumes:
      - {{ stage_dir }}/httpd-confs/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - {{ stage_dir }}/httpd-confs/httpd-vhosts-noctua.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    ports:
      - "{{noctua_proxy_port }}:80"
    depends_on:
      - noctua 

